### ISSUE TITLE
Retries entire block, instead of the failing command?

### ISSUE THREAD

**Issue by jpmckinney** [chmurph2/NiFTP#2]
From my reading of the code, if an FTP command fails (say, the 100th command), NiFTP will establish a new connection to the server and then re-perform all those commands?

**Comment by chmurph2** [comment]
I think you're right. :/  Perhaps the retryable block should just wrap [line 21](https://github.com/chmurph2/NiFTP/blob/master/lib/niftp.rb#L21), but it would still end up retrying all the commands again if there is an exception.

For situations where one doesn't want it to retry, the `tries` option can be set to `1`.

**Comment by jpmckinney** [comment]
I don't have it as a gem yet, but I wrote a subclass of Net::FTP that stores the arguments to `initialize` and tracks the cwd by overriding `chdir` (and calling `super` otherwise) so that when there's an error, I can retry with a fresh FTP client that `chdir`'s to the correct directory before retrying the command that failed.

**Comment by chmurph2** [comment]
I refreshed my memory on when/why I wrote this gem.  I was dealing with flakey FTP servers that wouldn't always connect/login on the first try, or would intermittently fail on FTP commands once it did. That's why the retryable block wraps the new connection plus the commands.

I've been using the library for several years now for commands that are idempotent.  If not, I'd set `tries` to `1`.

**Comment by jpmckinney** [comment]
Re-connecting once per command is expensive, and changing tries to 1 defeats the purpose of using the gem, which is to be able to retry failed commands.

**Comment by chmurph2** [comment]
I believe this gem makes using the Ruby FTP library easier to use for straightforward FTP usage, (e.g. connect, pull down a file, disconnect, retry once if there was a problem).  It also adds a way to timeout authentication, so it doesn't just sit there trying to connect.  If you don't find that useful or your needs are more involved, fair enough.  Thanks for the feedback.
